version: '3'
services:
  app:
    build:
      context: .
    ports: 
      - "80:8000"
    volumes:
      - ./:/code
    depends_on: [db]
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - c:/Users/J31640/volumes/mysql:/var/lib/mysql