version: '3'
services:
  web:
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
  app:
    build:
      context: .
    depends_on: [db]
  db:
    image: mysql:5.7